server:
  port: 0
spring:
  application:
    name: spring-cloud-order-service
'@zone': nh
'@datacenter': idc-nh
eureka:
  client:
    region: idc
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/eureka/
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${random.int}
orderclient:
  ribbon:
    ConnectTimeout: 2000
    ReadTimeout: 2000
    hystrixTimeout: 1000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    ServerListRefreshInterval: 2000
archaius:
  fixedDelayPollingScheduler:
    init‌​ialDelayMills: 5000
    dela‌​yMills: 30000
management:
  security:
    enabled: false
my:
  name: mary2
business:
  id1: foo1
  id2: bar