server:
  port: 9000
spring:
  application:
    name: spring-cloud-zuul
'@zone': nh
'@datacenter': idc-nh
eureka:
  client:
    region: idc
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/eureka/
    register-with-eureka: true
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
management:
  security:
    enabled: false